openapi: 3.0.3
info:
  title: Investor Vinci Stock eXchange Service
  description: Microservice handling the account of the investors
  version: 1.0.0
servers:
  - url: 'https'
paths:

  /users/{email}:
    parameters:
      - name: email
        in: path
        schema:
          type: string
        example: investor@hotmail.com
        description: Email of the user

    post:
      summary: Create a user
      requestBody:
        description: User to create
        content:
          'application/json':
            schema:
              $ref: '#/components/schemas/user'
      responses:
        400:
          description: Email does not match or user invalid
        409:
          description: Email already used
        201:
          description: User created

    put:
      summary: Update a user
      requestBody:
        description: New values of the user
        content:
          'application/json':
            schema:
              $ref: '#/components/schemas/user'
      responses:
        400:
          description: Email does not match or user invalid
        404:
          description: Email not found
        200:
          description: User updated

    delete:
      summary: Delete a user
      responses:
        404:
          description: Email not found
        200:
          description: User deleted

components:
  schemas:
    user:
      type: object
      properties:
        email:
          type: string
          description: email adress of the investor
        firstname:
          type: string
          description: surname of the investor
        lastname:
          type: string
          description: name of the investor
      example:
        pseudo: investor@hotmail.com
        firstname: Inv
        lastname: Estor