### Create an user
POST http://localhost:9006/investor/testuser
Content-Type: application/json

{
  "username": "testuser",
  "email": "testuser@example.com",
  "firstname": "John",
  "lastname": "Doe",
  "birthdate": "1990-01-01"
}

### create second user
POST http://localhost:9006/investor/billy
Content-Type: application/json

{
"username": "billy",
"email": "testuser@example.com",
"firstname": "John",
"lastname": "Doe",
"birthdate": "1990-01-01"
}
### get last price of AAPL
GET http://localhost:9003/price/AAPL


### get last price of PYPL
GET http://localhost:9003/price/PYPL

### Patch last price of PYPL
PATCH http://localhost:9003/price/PYPL
Content-Type: application/json

10


### add positions in an investor wallet
POST http://localhost:9005/wallet/billy
Content-Type: application/json

[
  {
    "ticker": "PYPL",
    "quantity": 10
  },
  {
    "ticker": "CASH",
    "quantity": 100
  }
]


### net worth of an investor
GET http://localhost:9005/wallet/billy/net-worth


### get all open positions
GET http://localhost:9005/billy/positions

### get all positions
GET http://localhost:9005/billy/all-positions




