### Create an user
POST http://localhost:9006/investor
Content-Type: application/json

{
  "username": "testuser",
  "email": "testuser@example.com",
  "firstname": "John",
  "lastname": "Doe",
  "birthdate": "1990-01-01"
}

### create second user
POST http://localhost:9006/investor
Content-Type: application/json

{
"username": "billy",
"email": "testuser@example.com",
"firstname": "John",
"lastname": "Doe",
"birthdate": "1990-01-01"
}

### net worth of an investor
GET http://localhost:9005/wallet/billy/net-worth


### get last price of AAPL
GET http://localhost:9003/price/AAPL


### get last price of MSFT
GET http://localhost:9003/price/MSFT

### Patch last price of AAPL
PATCH http://localhost:9003/price/AAPL
Content-Type: application/json

3

### add positions in an investor wallet
POST http://localhost:9005/wallet/testuser
Content-Type: application/json

[
  {
    "ticker": "AAPL",
    "quantity": 5
  },
  {
    "ticker": "MSFT",
    "quantity": 1
  }
]

### get all open positions
GET http://localhost:9005/testuser/positions

### get all positions
GET http://localhost:9005/testuser/all-positions



