### Exécution d'un ordre d'achat de type LIMIT pour l'action AAPL
POST http://localhost:9004/trigger/AAPL
Content-Type: application/json

{
  "guid": "1234",
  "owner": "Alice",
  "ticker": "AAPL",
  "quantity": 100,
  "type": "LIMIT",
  "side": "BUY",
  "limit": 150.0,
  "filled": 0
}


### Exécution d'un ordre d'achat de type MARKET pour l'action AAPL
POST http://localhost:9004/trigger/AAPL
Content-Type: application/json

{
"guid": "5678",
"owner": "Bob",
"ticker": "AAPL",
"quantity": 200,
"type": "MARKET",
"side": "BUY",
"limit": null,
"filled": 0
}

### Exécution d'un ordre de vente de type LIMIT pour l'action AAPL
POST http://localhost:9004/trigger/AAPL
Content-Type: application/json

{
"guid": "91011",
"owner": "Charlie",
"ticker": "AAPL",
"quantity": 150,
"type": "LIMIT",
"side": "SELL",
"limit": 160.0,
"filled": 0
}

### Exécution d'un ordre de vente de type MARKET pour l'action AAPL
POST http://localhost:9004/trigger/AAPL
Content-Type: application/json

{
"guid": "121314",
"owner": "David",
"ticker": "AAPL",
"quantity": 50,
"type": "MARKET",
"side": "SELL",
"limit": null,
"filled": 0
}
