### Create Investor
POST http://localhost:8080/investor/Test1
Content-Type: application/json

{
  "username": "Test1",
  "email": "testuser@example.com",
  "firstname": "John",
  "lastname": "Doe",
  "birthdate": "1990-01-01",
  "password": "PW1"
}

### Connect Investor
POST http://localhost:8080/authentication/connect
Content-Type: application/json

{
  "username": "Test1",
  "password": "PW1"
}