### Create Investor
POST http://localhost:8080/investor/TestInvestor
Content-Type: application/json

{
  "username": "TestInvestor",
  "email": "testinvestor@example.com",
  "firstname": "John",
  "lastname": "Wick",
  "birthdate": "1990-01-01",
  "password": "PW1"
}

### Connect Investor
POST http://localhost:8080/authentication/connect
Content-Type: application/json

{
  "username": "TestInvestor",
  "password": "PW1"
}